'use client';

import { useEffect, useState } from 'react';
import {
  generateAnalyticsSummary,
  type GenerateAnalyticsSummaryInput,
  type GenerateAnalyticsSummaryOutput,
} from '@/ai/flows/generate-analytics-summary';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Sparkles, Loader2 } from 'lucide-react';

interface AnalyticsSummaryProps {
  data: GenerateAnalyticsSummaryInput;
}

export default function AnalyticsSummary({ data }: AnalyticsSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchSummary = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result: GenerateAnalyticsSummaryOutput = await generateAnalyticsSummary(data);
      setSummary(result.summary);
    } catch (e) {
      setError('Failed to generate summary. Please try again.');
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data.totalRooms, data.roomsBookedToday, data.totalUsers, data.upcomingCheckIns]);

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 font-headline">
          <Sparkles className="text-accent" />
          AI-Powered Analytics Summary
        </CardTitle>
        <CardDescription>A concise overview generated by AI.</CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex items-center gap-2 text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            <span>Generating summary...</span>
          </div>
        ) : error ? (
          <div className="text-destructive">
            <p>{error}</p>
            <Button variant="link" onClick={fetchSummary} className="p-0 h-auto mt-2">
              Retry
            </Button>
          </div>
        ) : (
          <p className="text-lg italic">&ldquo;{summary}&rdquo;</p>
        )}
      </CardContent>
    </Card>
  );
}
